### ISSUE TITLE
关于分布式爬虫的一个疑问

### ISSUE THREAD

**Issue by wuxiongliu1** [Python3WebSpider/Weibo#1]
博主，您好，我最近在看您的《Python3 网络爬虫开发实战》中的分布式爬虫章节，里面讲到了利用scrapy-redis 来实现分布式的爬虫。我有点疑惑的是，假设有5 个一模一样的爬虫运行在不同的机器上，在代码上看的化，每个爬虫其实都是从start_urls 开始的，既然这五个爬虫都是一样的，那启动起来之后这5个爬虫不是做了一模一样的事情吗，虽然redis 可以去重，但是这五个爬虫其实都是重复了向redis发送了5份统一的requests 数据到redis，这不是很奇怪吗？ 能否只有一个爬虫启动的时候是从start_urls 中开始，其余的4个其实是从redis 中直接开始的，而不是从start_urls 中开始呢？

**Comment by Germey** [comment]
并不是，爬虫启动时会先检测队列有无requests，如果有，就直接取，否则才执行 start requests

**Comment by wuxiongliu1** [comment]
爬虫启动后，会yield 列表url 和详情的url。我有这三个疑问
1. 放入redis 的是requests 是这两中url 的requests 吗？
2. 爬虫从url拿到requests ，怎么区分是列表url 还是详情的url呢？
3. 分布式爬虫的spider 是要继承RedisSpider 的吗

**Comment by aesdhj** [comment]
我也在看这本书，为这本书建了一个QQ群805370297，方便大家讨论

**Comment by Mrrrrr10** [comment]
楼主，请问一下，这种爬取的方式不需要cookie吧？但是数据爬取的不完整，特别是用户发表的微博

**Comment by Germey** [comment]
@Mrrrrr10 微博的 API 不用 Cookies 也能爬，但是确实会有不完整的现象，所以也建议对接 Cookies 池

**Comment by Mrrrrr10** [comment]
楼主楼主，对接cookie数据全不全，谢谢楼主解答

**Comment by Germey** [comment]
这个主要看账号了，如果你的账号是被爬者的好友或者本人，那当然爬取的结果更全，但一般来说都是买的普通小号，能看到的就少一些了。
所以对每个账号来说，都是可见即可爬，看你用的什么账号了。

**Comment by Mrrrrr10** [comment]
感谢楼主解答，最后一个问题，weibo.cn的cookie池可以用于m.weibo.com这个站点吗？刚看完你的视频，收获很多

**Comment by Mrrrrr10** [comment]
手动@Germey
