### ISSUE TITLE
关于启动分布式爬虫的疑问

### ISSUE THREAD

**Issue by Mrtrl** [Python3WebSpider/Weibo#3]

**Comment by Mrtrl** [comment]
博主你好,我看了《python3网络爬虫》跟着书本上的步骤来实现scrapy-redis爬虫，但是，我发现我的爬虫跑起来之后并没有跟redis对接上，两个爬虫都是各跑各的，然后我看了scrapy-redis的官方Demo，spider是需要继承Redisspider的。但是我发现你的代码里面并没有，请问这是为什么呢？

**Comment by fgksgf** [comment]
@Germey 同问

**Comment by framelei** [comment]
同疑问 @Germey

**Comment by Mrtrl** [comment]
@framelei 这个问题我解决了，我当时出现的问题是yield request的时候加了dont_filter=True

**Comment by framelei** [comment]
@Mrtrl 请问分布式爬虫，spider需要继承Redisspider的，博主不继承没关系吗

**Comment by Mrtrl** [comment]
不需要继承

**Comment by luanguang** [comment]
@Mrtrl  没有继承，在settings里面也没有设置……这没搞明白……能稍微讲解一下吗？拜托了。

**Comment by Mrtrl** [comment]
@luanguang 你是设置了还没用不了scrapy-redis么？
